# -*- coding: utf-8 -*-
"""FACTORICAL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P9SweXQL4RkO9R3DWvKqk1Cf9b4BZCLr

Factorial of Number
"""

vv

n=5
fact=1
for i in range(1,n+1):
    fact = fact*i
print(fact)